variables:
  baseName: adbsccstd0419
  env: dev
  resourcegroup: rg-wus2-$(baseName)-dev
  vnetresourcegroup: rg-wus2-$(baseName)-net-dev
  transitresourcegroup: rg-wus2-$(baseName)-trans-dev
  vnetname: $(baseName)$(env)-vnet
  location: westus2
