variables:
  baseName: adb3600402
  resourcegroup: rg-wus2-$(baseName)-prd  
  location: westus2
  kvsreadersgroupoid: 805f7bfc-80cf-4f21-8a2a-acba919a1409
  kvadminsoid: 4a16f19d-952d-48a2-9999-0d9bf119a405
  
