name: iac-test-pipeline

trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: iactest
  displayName: 'Run iac tests'
  jobs:
  - job: RunTests
    displayName: 'Run pytest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip setuptools
        pip install pytest python-dotenv requests
      displayName: 'Install pytest'

    - script: |
        pytest ./iac-adb-360/tests/iac_tests.py
      displayName: 'Run iac tests'