trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'

variables:
- group: vgdevadb360

stages:
- stage: stg_init_with_volume
  displayName: 'create bronze volume'
  jobs:
  - job: j_init_with_volume
    displayName: 'job create bronze volume'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Install Databricks CLI v 2'


    - task: AzureCLI@2
      displayName: 'validate bundle'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        scriptPath: |
          cd bundle_adb_360 
          databricks bundle validate -t $(env)


    - task: AzureCLI@2
      displayName: call script to deploy bundle'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: './bundle_adb_360/helpers/bundle-deploy.sh'
        arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(env)'

