name: PostMetastoreCombinedDeploy

on:
  push:
    branches:
      - devy
    paths:
      - '**'
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  ENV: ${{ github.ref_name }}

jobs:
  assign-repo:
    name: Assign Repository to SPN
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make the script executable
        run: chmod +x ./iac-adb-360/helpers/attach-to-repo-github.sh

      - name: Assign repo to SPN
        run: ./iac-adb-360/helpers/attach-to-repo-github.sh ${{ vars.RESOURCE_GROUP }} ${{ vars.TENANT_ID }} ${{ vars.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ vars.REPO_URL }} ${{ vars.GH_USER }} ${{ secrets.GH_PAT }}


  create-catalog-and-schema:
    name: Create Catalog and Schema
    needs: assign-repo
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make the script executable
        run: chmod +x ./iac-adb-360/helpers/create-ms-catalognschema-sepstor.sh

      - name: Assign repo to SPN
        run: ./iac-adb-360/helpers/create-ms-catalognschema-sepstor.sh ${{ vars.RESOURCE_GROUP }} ${{ vars.TENANT_ID }} ${{ vars.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ vars.METASTORE_NAME }} ${{ env.ENV }} ${{ vars.CATALOG_STORAGE_ACCOUNT_NAME }} ${{ vars.CRED_NAME }} ${{ vars.ACCESS_CONNECTOR_ID }}
      
      - name: Make the script executable
        run: chmod +x ./iac-adb-360/helpers/create-ms-externallocation.sh

      - name: Assign repo to SPN
        run: ./iac-adb-360/helpers/create-ms-externallocation.sh ${{ vars.RESOURCE_GROUP }} ${{ vars.TENANT_ID }} ${{ vars.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ vars.METASTORE_NAME }} ${{ env.ENV }} ${{ vars.BRONZE_STORAGE_ACCOUNT_NAME }} ${{ vars.CRED_NAME }} ${{ vars.ACCESS_CONNECTOR_ID }}



